### ISSUE TITLE
AttributeError: 'SteamClient' object has no attribute 'licenses'

### ISSUE THREAD

**Issue by PatrickJnr** [wynick27/steam-missing-covers-downloader#2]
```
Traceback (most recent call last):
  File "missing_cover_downloader.py", line 189, in <module>
    owned_packageids = get_owned_packages(client)
  File "missing_cover_downloader.py", line 20, in get_owned_packages
    if len(client.licenses) == 0:
AttributeError: 'SteamClient' object has no attribute 'licenses'
```

**Comment by wynick27** [comment]
It requires steam 1.0.0alpha, 0.9.1 from pypi doesn't have the required functions to check steam licenses. 1.0.0 can be downloaded using the following commands after uninstalling the old version:

```pip install git+https://github.com/ValvePython/steam#egg=steam
```

**Comment by PatrickJnr** [comment]
Thank you I've uninstalled the old version and reinstalled the new version, working fine now!
