### ISSUE TITLE
Scanning for non-game entries

### ISSUE THREAD

**Issue by SomeoneIsWorking** [wynick27/steam-missing-covers-downloader#20]
Non-game entries such as Gamepad Controller Template (1456390) cause Exception

```
Error finding cover for 1456390, Game not found
Total cover downloaded: 0
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001B5AC739240>
Traceback (most recent call last):
  File "C:\python3\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\python3\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\python3\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\python3\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by Jonius7** [comment]
Fixed in 407e820ec43b61d1f4329a4703a92010b6707ff2
